//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Date: 11/23/2020 07:36:19
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Scriban.Helpers;
using Scriban.Syntax;

namespace Kalk.Core.Modules
{
    public partial class VectorModule
    {
        private const string CategoryMatrixConstructors = "Type Matrix Constructors";

        
        private static readonly KalkVectorConstructor<byte> Byte16Constructor = new KalkVectorConstructor<byte>(16);
        
        private static readonly KalkVectorConstructor<byte> Byte32Constructor = new KalkVectorConstructor<byte>(32);
        
        private static readonly KalkVectorConstructor<byte> Byte64Constructor = new KalkVectorConstructor<byte>(64);
            
        private static readonly KalkVectorConstructor<sbyte> SByte16Constructor = new KalkVectorConstructor<sbyte>(16);
        
        private static readonly KalkVectorConstructor<sbyte> SByte32Constructor = new KalkVectorConstructor<sbyte>(32);
        
        private static readonly KalkVectorConstructor<sbyte> SByte64Constructor = new KalkVectorConstructor<sbyte>(64);
            
        private static readonly KalkVectorConstructor<short> Short2Constructor = new KalkVectorConstructor<short>(2);
        
        private static readonly KalkVectorConstructor<short> Short4Constructor = new KalkVectorConstructor<short>(4);
        
        private static readonly KalkVectorConstructor<short> Short8Constructor = new KalkVectorConstructor<short>(8);
        
        private static readonly KalkVectorConstructor<short> Short16Constructor = new KalkVectorConstructor<short>(16);
        
        private static readonly KalkVectorConstructor<short> Short32Constructor = new KalkVectorConstructor<short>(32);
            
        private static readonly KalkVectorConstructor<ushort> UShort2Constructor = new KalkVectorConstructor<ushort>(2);
        
        private static readonly KalkVectorConstructor<ushort> UShort4Constructor = new KalkVectorConstructor<ushort>(4);
        
        private static readonly KalkVectorConstructor<ushort> UShort8Constructor = new KalkVectorConstructor<ushort>(8);
        
        private static readonly KalkVectorConstructor<ushort> UShort16Constructor = new KalkVectorConstructor<ushort>(16);
        
        private static readonly KalkVectorConstructor<ushort> UShort32Constructor = new KalkVectorConstructor<ushort>(32);
            
        private static readonly KalkVectorConstructor<int> Int2Constructor = new KalkVectorConstructor<int>(2);
        
        private static readonly KalkVectorConstructor<int> Int3Constructor = new KalkVectorConstructor<int>(3);
        
        private static readonly KalkVectorConstructor<int> Int4Constructor = new KalkVectorConstructor<int>(4);
        
        private static readonly KalkVectorConstructor<int> Int8Constructor = new KalkVectorConstructor<int>(8);
        
        private static readonly KalkVectorConstructor<int> Int16Constructor = new KalkVectorConstructor<int>(16);
            
        private static readonly KalkVectorConstructor<uint> UInt2Constructor = new KalkVectorConstructor<uint>(2);
        
        private static readonly KalkVectorConstructor<uint> UInt3Constructor = new KalkVectorConstructor<uint>(3);
        
        private static readonly KalkVectorConstructor<uint> UInt4Constructor = new KalkVectorConstructor<uint>(4);
        
        private static readonly KalkVectorConstructor<uint> UInt8Constructor = new KalkVectorConstructor<uint>(8);
        
        private static readonly KalkVectorConstructor<uint> UInt16Constructor = new KalkVectorConstructor<uint>(16);
            
        private static readonly KalkVectorConstructor<long> Long2Constructor = new KalkVectorConstructor<long>(2);
        
        private static readonly KalkVectorConstructor<long> Long3Constructor = new KalkVectorConstructor<long>(3);
        
        private static readonly KalkVectorConstructor<long> Long4Constructor = new KalkVectorConstructor<long>(4);
        
        private static readonly KalkVectorConstructor<long> Long8Constructor = new KalkVectorConstructor<long>(8);
            
        private static readonly KalkVectorConstructor<ulong> ULong2Constructor = new KalkVectorConstructor<ulong>(2);
        
        private static readonly KalkVectorConstructor<ulong> ULong3Constructor = new KalkVectorConstructor<ulong>(3);
        
        private static readonly KalkVectorConstructor<ulong> ULong4Constructor = new KalkVectorConstructor<ulong>(4);
        
        private static readonly KalkVectorConstructor<ulong> ULong8Constructor = new KalkVectorConstructor<ulong>(8);
            
        private static readonly KalkVectorConstructor<KalkBool> Bool2Constructor = new KalkVectorConstructor<KalkBool>(2);
        
        private static readonly KalkVectorConstructor<KalkBool> Bool3Constructor = new KalkVectorConstructor<KalkBool>(3);
        
        private static readonly KalkVectorConstructor<KalkBool> Bool4Constructor = new KalkVectorConstructor<KalkBool>(4);
        
        private static readonly KalkVectorConstructor<KalkBool> Bool8Constructor = new KalkVectorConstructor<KalkBool>(8);
        
        private static readonly KalkVectorConstructor<KalkBool> Bool16Constructor = new KalkVectorConstructor<KalkBool>(16);
            
        private static readonly KalkVectorConstructor<float> Float2Constructor = new KalkVectorConstructor<float>(2);
        
        private static readonly KalkVectorConstructor<float> Float3Constructor = new KalkVectorConstructor<float>(3);
        
        private static readonly KalkVectorConstructor<float> Float4Constructor = new KalkVectorConstructor<float>(4);
        
        private static readonly KalkVectorConstructor<float> Float8Constructor = new KalkVectorConstructor<float>(8);
        
        private static readonly KalkVectorConstructor<float> Float16Constructor = new KalkVectorConstructor<float>(16);
            
        private static readonly KalkVectorConstructor<double> Double2Constructor = new KalkVectorConstructor<double>(2);
        
        private static readonly KalkVectorConstructor<double> Double3Constructor = new KalkVectorConstructor<double>(3);
        
        private static readonly KalkVectorConstructor<double> Double4Constructor = new KalkVectorConstructor<double>(4);
        
        private static readonly KalkVectorConstructor<double> Double8Constructor = new KalkVectorConstructor<double>(8);
    
        private static readonly KalkMatrixConstructor<KalkBool> Bool2x2Constructor = new KalkMatrixConstructor<KalkBool>(2, 2);
        private static readonly KalkMatrixConstructor<KalkBool> Bool2x3Constructor = new KalkMatrixConstructor<KalkBool>(2, 3);
        private static readonly KalkMatrixConstructor<KalkBool> Bool2x4Constructor = new KalkMatrixConstructor<KalkBool>(2, 4);
        private static readonly KalkMatrixConstructor<KalkBool> Bool3x2Constructor = new KalkMatrixConstructor<KalkBool>(3, 2);
        private static readonly KalkMatrixConstructor<KalkBool> Bool3x3Constructor = new KalkMatrixConstructor<KalkBool>(3, 3);
        private static readonly KalkMatrixConstructor<KalkBool> Bool3x4Constructor = new KalkMatrixConstructor<KalkBool>(3, 4);
        private static readonly KalkMatrixConstructor<KalkBool> Bool4x2Constructor = new KalkMatrixConstructor<KalkBool>(4, 2);
        private static readonly KalkMatrixConstructor<KalkBool> Bool4x3Constructor = new KalkMatrixConstructor<KalkBool>(4, 3);
        private static readonly KalkMatrixConstructor<KalkBool> Bool4x4Constructor = new KalkMatrixConstructor<KalkBool>(4, 4);
        private static readonly KalkMatrixConstructor<int> Int2x2Constructor = new KalkMatrixConstructor<int>(2, 2);
        private static readonly KalkMatrixConstructor<int> Int2x3Constructor = new KalkMatrixConstructor<int>(2, 3);
        private static readonly KalkMatrixConstructor<int> Int2x4Constructor = new KalkMatrixConstructor<int>(2, 4);
        private static readonly KalkMatrixConstructor<int> Int3x2Constructor = new KalkMatrixConstructor<int>(3, 2);
        private static readonly KalkMatrixConstructor<int> Int3x3Constructor = new KalkMatrixConstructor<int>(3, 3);
        private static readonly KalkMatrixConstructor<int> Int3x4Constructor = new KalkMatrixConstructor<int>(3, 4);
        private static readonly KalkMatrixConstructor<int> Int4x2Constructor = new KalkMatrixConstructor<int>(4, 2);
        private static readonly KalkMatrixConstructor<int> Int4x3Constructor = new KalkMatrixConstructor<int>(4, 3);
        private static readonly KalkMatrixConstructor<int> Int4x4Constructor = new KalkMatrixConstructor<int>(4, 4);
        private static readonly KalkMatrixConstructor<float> Float2x2Constructor = new KalkMatrixConstructor<float>(2, 2);
        private static readonly KalkMatrixConstructor<float> Float2x3Constructor = new KalkMatrixConstructor<float>(2, 3);
        private static readonly KalkMatrixConstructor<float> Float2x4Constructor = new KalkMatrixConstructor<float>(2, 4);
        private static readonly KalkMatrixConstructor<float> Float3x2Constructor = new KalkMatrixConstructor<float>(3, 2);
        private static readonly KalkMatrixConstructor<float> Float3x3Constructor = new KalkMatrixConstructor<float>(3, 3);
        private static readonly KalkMatrixConstructor<float> Float3x4Constructor = new KalkMatrixConstructor<float>(3, 4);
        private static readonly KalkMatrixConstructor<float> Float4x2Constructor = new KalkMatrixConstructor<float>(4, 2);
        private static readonly KalkMatrixConstructor<float> Float4x3Constructor = new KalkMatrixConstructor<float>(4, 3);
        private static readonly KalkMatrixConstructor<float> Float4x4Constructor = new KalkMatrixConstructor<float>(4, 4);
        private static readonly KalkMatrixConstructor<double> Double2x2Constructor = new KalkMatrixConstructor<double>(2, 2);
        private static readonly KalkMatrixConstructor<double> Double2x3Constructor = new KalkMatrixConstructor<double>(2, 3);
        private static readonly KalkMatrixConstructor<double> Double2x4Constructor = new KalkMatrixConstructor<double>(2, 4);
        private static readonly KalkMatrixConstructor<double> Double3x2Constructor = new KalkMatrixConstructor<double>(3, 2);
        private static readonly KalkMatrixConstructor<double> Double3x3Constructor = new KalkMatrixConstructor<double>(3, 3);
        private static readonly KalkMatrixConstructor<double> Double3x4Constructor = new KalkMatrixConstructor<double>(3, 4);
        private static readonly KalkMatrixConstructor<double> Double4x2Constructor = new KalkMatrixConstructor<double>(4, 2);
        private static readonly KalkMatrixConstructor<double> Double4x3Constructor = new KalkMatrixConstructor<double>(4, 3);
        private static readonly KalkMatrixConstructor<double> Double4x4Constructor = new KalkMatrixConstructor<double>(4, 4);

        /// <summary>Creates a vector of 16 `byte` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> byte16(1..16)
        /// # byte16(1..16)
        /// out = byte16(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
        /// >>> byte16(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
        /// # byte16(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
        /// out = byte16(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
        /// ```
        /// </example>
        [KalkExport("byte16", CategoryVectorTypeConstructors)]
        public KalkVector<byte> CreateByte16(params object[] arguments) => Byte16Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 32 `byte` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> byte32(1..32)
        /// # byte32(1..32)
        /// out = byte32(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32)
        /// ```
        /// </example>
        [KalkExport("byte32", CategoryVectorTypeConstructors)]
        public KalkVector<byte> CreateByte32(params object[] arguments) => Byte32Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 64 `byte` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> byte64(1..64)
        /// # byte64(1..64)
        /// out = byte64(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64)
        /// ```
        /// </example>
        [KalkExport("byte64", CategoryVectorTypeConstructors)]
        public KalkVector<byte> CreateByte64(params object[] arguments) => Byte64Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 16 `sbyte` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> sbyte16(1..16)
        /// # sbyte16(1..16)
        /// out = sbyte16(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
        /// >>> sbyte16(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
        /// # sbyte16(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
        /// out = sbyte16(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
        /// ```
        /// </example>
        [KalkExport("sbyte16", CategoryVectorTypeConstructors)]
        public KalkVector<sbyte> CreateSByte16(params object[] arguments) => SByte16Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 32 `sbyte` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> sbyte32(1..32)
        /// # sbyte32(1..32)
        /// out = sbyte32(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32)
        /// ```
        /// </example>
        [KalkExport("sbyte32", CategoryVectorTypeConstructors)]
        public KalkVector<sbyte> CreateSByte32(params object[] arguments) => SByte32Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 64 `sbyte` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> sbyte64(1..64)
        /// # sbyte64(1..64)
        /// out = sbyte64(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64)
        /// ```
        /// </example>
        [KalkExport("sbyte64", CategoryVectorTypeConstructors)]
        public KalkVector<sbyte> CreateSByte64(params object[] arguments) => SByte64Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 2 `short` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> short2(1..2)
        /// # short2(1..2)
        /// out = short2(1, 2)
        /// >>> short2(10, 11)
        /// # short2(10, 11)
        /// out = short2(10, 11)
        /// ```
        /// </example>
        [KalkExport("short2", CategoryVectorTypeConstructors)]
        public KalkVector<short> CreateShort2(params object[] arguments) => Short2Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 4 `short` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> short4(1..4)
        /// # short4(1..4)
        /// out = short4(1, 2, 3, 4)
        /// >>> short4(10, 11, 12, 13)
        /// # short4(10, 11, 12, 13)
        /// out = short4(10, 11, 12, 13)
        /// ```
        /// </example>
        [KalkExport("short4", CategoryVectorTypeConstructors)]
        public KalkVector<short> CreateShort4(params object[] arguments) => Short4Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 8 `short` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> short8(1..8)
        /// # short8(1..8)
        /// out = short8(1, 2, 3, 4, 5, 6, 7, 8)
        /// >>> short8(10, 11, 12, 13, 14, 15, 16, 17)
        /// # short8(10, 11, 12, 13, 14, 15, 16, 17)
        /// out = short8(10, 11, 12, 13, 14, 15, 16, 17)
        /// ```
        /// </example>
        [KalkExport("short8", CategoryVectorTypeConstructors)]
        public KalkVector<short> CreateShort8(params object[] arguments) => Short8Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 16 `short` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> short16(1..16)
        /// # short16(1..16)
        /// out = short16(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
        /// >>> short16(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
        /// # short16(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
        /// out = short16(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
        /// ```
        /// </example>
        [KalkExport("short16", CategoryVectorTypeConstructors)]
        public KalkVector<short> CreateShort16(params object[] arguments) => Short16Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 32 `short` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> short32(1..32)
        /// # short32(1..32)
        /// out = short32(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32)
        /// ```
        /// </example>
        [KalkExport("short32", CategoryVectorTypeConstructors)]
        public KalkVector<short> CreateShort32(params object[] arguments) => Short32Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 2 `ushort` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> ushort2(1..2)
        /// # ushort2(1..2)
        /// out = ushort2(1, 2)
        /// >>> ushort2(10, 11)
        /// # ushort2(10, 11)
        /// out = ushort2(10, 11)
        /// ```
        /// </example>
        [KalkExport("ushort2", CategoryVectorTypeConstructors)]
        public KalkVector<ushort> CreateUShort2(params object[] arguments) => UShort2Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 4 `ushort` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> ushort4(1..4)
        /// # ushort4(1..4)
        /// out = ushort4(1, 2, 3, 4)
        /// >>> ushort4(10, 11, 12, 13)
        /// # ushort4(10, 11, 12, 13)
        /// out = ushort4(10, 11, 12, 13)
        /// ```
        /// </example>
        [KalkExport("ushort4", CategoryVectorTypeConstructors)]
        public KalkVector<ushort> CreateUShort4(params object[] arguments) => UShort4Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 8 `ushort` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> ushort8(1..8)
        /// # ushort8(1..8)
        /// out = ushort8(1, 2, 3, 4, 5, 6, 7, 8)
        /// >>> ushort8(10, 11, 12, 13, 14, 15, 16, 17)
        /// # ushort8(10, 11, 12, 13, 14, 15, 16, 17)
        /// out = ushort8(10, 11, 12, 13, 14, 15, 16, 17)
        /// ```
        /// </example>
        [KalkExport("ushort8", CategoryVectorTypeConstructors)]
        public KalkVector<ushort> CreateUShort8(params object[] arguments) => UShort8Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 16 `ushort` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> ushort16(1..16)
        /// # ushort16(1..16)
        /// out = ushort16(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
        /// >>> ushort16(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
        /// # ushort16(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
        /// out = ushort16(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
        /// ```
        /// </example>
        [KalkExport("ushort16", CategoryVectorTypeConstructors)]
        public KalkVector<ushort> CreateUShort16(params object[] arguments) => UShort16Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 32 `ushort` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> ushort32(1..32)
        /// # ushort32(1..32)
        /// out = ushort32(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32)
        /// ```
        /// </example>
        [KalkExport("ushort32", CategoryVectorTypeConstructors)]
        public KalkVector<ushort> CreateUShort32(params object[] arguments) => UShort32Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 2 `int` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> int2(1..2)
        /// # int2(1..2)
        /// out = int2(1, 2)
        /// >>> int2(10, 11)
        /// # int2(10, 11)
        /// out = int2(10, 11)
        /// ```
        /// </example>
        [KalkExport("int2", CategoryVectorTypeConstructors)]
        public KalkVector<int> CreateInt2(params object[] arguments) => Int2Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 3 `int` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> int3(1..3)
        /// # int3(1..3)
        /// out = int3(1, 2, 3)
        /// >>> int3(10, 11, 12)
        /// # int3(10, 11, 12)
        /// out = int3(10, 11, 12)
        /// ```
        /// </example>
        [KalkExport("int3", CategoryVectorTypeConstructors)]
        public KalkVector<int> CreateInt3(params object[] arguments) => Int3Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 4 `int` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> int4(1..4)
        /// # int4(1..4)
        /// out = int4(1, 2, 3, 4)
        /// >>> int4(10, 11, 12, 13)
        /// # int4(10, 11, 12, 13)
        /// out = int4(10, 11, 12, 13)
        /// ```
        /// </example>
        [KalkExport("int4", CategoryVectorTypeConstructors)]
        public KalkVector<int> CreateInt4(params object[] arguments) => Int4Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 8 `int` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> int8(1..8)
        /// # int8(1..8)
        /// out = int8(1, 2, 3, 4, 5, 6, 7, 8)
        /// >>> int8(10, 11, 12, 13, 14, 15, 16, 17)
        /// # int8(10, 11, 12, 13, 14, 15, 16, 17)
        /// out = int8(10, 11, 12, 13, 14, 15, 16, 17)
        /// ```
        /// </example>
        [KalkExport("int8", CategoryVectorTypeConstructors)]
        public KalkVector<int> CreateInt8(params object[] arguments) => Int8Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 16 `int` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> int16(1..16)
        /// # int16(1..16)
        /// out = int16(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
        /// >>> int16(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
        /// # int16(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
        /// out = int16(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
        /// ```
        /// </example>
        [KalkExport("int16", CategoryVectorTypeConstructors)]
        public KalkVector<int> CreateInt16(params object[] arguments) => Int16Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 2 `uint` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> uint2(1..2)
        /// # uint2(1..2)
        /// out = uint2(1, 2)
        /// >>> uint2(10, 11)
        /// # uint2(10, 11)
        /// out = uint2(10, 11)
        /// ```
        /// </example>
        [KalkExport("uint2", CategoryVectorTypeConstructors)]
        public KalkVector<uint> CreateUInt2(params object[] arguments) => UInt2Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 3 `uint` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> uint3(1..3)
        /// # uint3(1..3)
        /// out = uint3(1, 2, 3)
        /// >>> uint3(10, 11, 12)
        /// # uint3(10, 11, 12)
        /// out = uint3(10, 11, 12)
        /// ```
        /// </example>
        [KalkExport("uint3", CategoryVectorTypeConstructors)]
        public KalkVector<uint> CreateUInt3(params object[] arguments) => UInt3Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 4 `uint` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> uint4(1..4)
        /// # uint4(1..4)
        /// out = uint4(1, 2, 3, 4)
        /// >>> uint4(10, 11, 12, 13)
        /// # uint4(10, 11, 12, 13)
        /// out = uint4(10, 11, 12, 13)
        /// ```
        /// </example>
        [KalkExport("uint4", CategoryVectorTypeConstructors)]
        public KalkVector<uint> CreateUInt4(params object[] arguments) => UInt4Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 8 `uint` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> uint8(1..8)
        /// # uint8(1..8)
        /// out = uint8(1, 2, 3, 4, 5, 6, 7, 8)
        /// >>> uint8(10, 11, 12, 13, 14, 15, 16, 17)
        /// # uint8(10, 11, 12, 13, 14, 15, 16, 17)
        /// out = uint8(10, 11, 12, 13, 14, 15, 16, 17)
        /// ```
        /// </example>
        [KalkExport("uint8", CategoryVectorTypeConstructors)]
        public KalkVector<uint> CreateUInt8(params object[] arguments) => UInt8Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 16 `uint` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> uint16(1..16)
        /// # uint16(1..16)
        /// out = uint16(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
        /// >>> uint16(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
        /// # uint16(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
        /// out = uint16(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
        /// ```
        /// </example>
        [KalkExport("uint16", CategoryVectorTypeConstructors)]
        public KalkVector<uint> CreateUInt16(params object[] arguments) => UInt16Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 2 `long` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> long2(1..2)
        /// # long2(1..2)
        /// out = long2(1, 2)
        /// >>> long2(10, 11)
        /// # long2(10, 11)
        /// out = long2(10, 11)
        /// ```
        /// </example>
        [KalkExport("long2", CategoryVectorTypeConstructors)]
        public KalkVector<long> CreateLong2(params object[] arguments) => Long2Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 3 `long` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> long3(1..3)
        /// # long3(1..3)
        /// out = long3(1, 2, 3)
        /// >>> long3(10, 11, 12)
        /// # long3(10, 11, 12)
        /// out = long3(10, 11, 12)
        /// ```
        /// </example>
        [KalkExport("long3", CategoryVectorTypeConstructors)]
        public KalkVector<long> CreateLong3(params object[] arguments) => Long3Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 4 `long` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> long4(1..4)
        /// # long4(1..4)
        /// out = long4(1, 2, 3, 4)
        /// >>> long4(10, 11, 12, 13)
        /// # long4(10, 11, 12, 13)
        /// out = long4(10, 11, 12, 13)
        /// ```
        /// </example>
        [KalkExport("long4", CategoryVectorTypeConstructors)]
        public KalkVector<long> CreateLong4(params object[] arguments) => Long4Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 8 `long` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> long8(1..8)
        /// # long8(1..8)
        /// out = long8(1, 2, 3, 4, 5, 6, 7, 8)
        /// >>> long8(10, 11, 12, 13, 14, 15, 16, 17)
        /// # long8(10, 11, 12, 13, 14, 15, 16, 17)
        /// out = long8(10, 11, 12, 13, 14, 15, 16, 17)
        /// ```
        /// </example>
        [KalkExport("long8", CategoryVectorTypeConstructors)]
        public KalkVector<long> CreateLong8(params object[] arguments) => Long8Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 2 `ulong` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> ulong2(1..2)
        /// # ulong2(1..2)
        /// out = ulong2(1, 2)
        /// >>> ulong2(10, 11)
        /// # ulong2(10, 11)
        /// out = ulong2(10, 11)
        /// ```
        /// </example>
        [KalkExport("ulong2", CategoryVectorTypeConstructors)]
        public KalkVector<ulong> CreateULong2(params object[] arguments) => ULong2Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 3 `ulong` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> ulong3(1..3)
        /// # ulong3(1..3)
        /// out = ulong3(1, 2, 3)
        /// >>> ulong3(10, 11, 12)
        /// # ulong3(10, 11, 12)
        /// out = ulong3(10, 11, 12)
        /// ```
        /// </example>
        [KalkExport("ulong3", CategoryVectorTypeConstructors)]
        public KalkVector<ulong> CreateULong3(params object[] arguments) => ULong3Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 4 `ulong` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> ulong4(1..4)
        /// # ulong4(1..4)
        /// out = ulong4(1, 2, 3, 4)
        /// >>> ulong4(10, 11, 12, 13)
        /// # ulong4(10, 11, 12, 13)
        /// out = ulong4(10, 11, 12, 13)
        /// ```
        /// </example>
        [KalkExport("ulong4", CategoryVectorTypeConstructors)]
        public KalkVector<ulong> CreateULong4(params object[] arguments) => ULong4Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 8 `ulong` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> ulong8(1..8)
        /// # ulong8(1..8)
        /// out = ulong8(1, 2, 3, 4, 5, 6, 7, 8)
        /// >>> ulong8(10, 11, 12, 13, 14, 15, 16, 17)
        /// # ulong8(10, 11, 12, 13, 14, 15, 16, 17)
        /// out = ulong8(10, 11, 12, 13, 14, 15, 16, 17)
        /// ```
        /// </example>
        [KalkExport("ulong8", CategoryVectorTypeConstructors)]
        public KalkVector<ulong> CreateULong8(params object[] arguments) => ULong8Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 2 `bool` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> bool2(true)
        /// # bool2(true)
        /// out = bool2(true, true)
        /// ```
        /// </example>
        [KalkExport("bool2", CategoryVectorTypeConstructors)]
        public KalkVector<KalkBool> CreateBool2(params object[] arguments) => Bool2Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 3 `bool` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> bool3(true)
        /// # bool3(true)
        /// out = bool3(true, true, true)
        /// ```
        /// </example>
        [KalkExport("bool3", CategoryVectorTypeConstructors)]
        public KalkVector<KalkBool> CreateBool3(params object[] arguments) => Bool3Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 4 `bool` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> bool4(true)
        /// # bool4(true)
        /// out = bool4(true, true, true, true)
        /// ```
        /// </example>
        [KalkExport("bool4", CategoryVectorTypeConstructors)]
        public KalkVector<KalkBool> CreateBool4(params object[] arguments) => Bool4Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 8 `bool` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> bool8(true)
        /// # bool8(true)
        /// out = bool8(true, true, true, true, true, true, true, true)
        /// ```
        /// </example>
        [KalkExport("bool8", CategoryVectorTypeConstructors)]
        public KalkVector<KalkBool> CreateBool8(params object[] arguments) => Bool8Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 16 `bool` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> bool16(true)
        /// # bool16(true)
        /// out = bool16(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true)
        /// ```
        /// </example>
        [KalkExport("bool16", CategoryVectorTypeConstructors)]
        public KalkVector<KalkBool> CreateBool16(params object[] arguments) => Bool16Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 2 `float` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> float2(1..2)
        /// # float2(1..2)
        /// out = float2(1, 2)
        /// >>> float2(10, 11)
        /// # float2(10, 11)
        /// out = float2(10, 11)
        /// ```
        /// </example>
        [KalkExport("float2", CategoryVectorTypeConstructors)]
        public KalkVector<float> CreateFloat2(params object[] arguments) => Float2Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 3 `float` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> float3(1..3)
        /// # float3(1..3)
        /// out = float3(1, 2, 3)
        /// >>> float3(10, 11, 12)
        /// # float3(10, 11, 12)
        /// out = float3(10, 11, 12)
        /// ```
        /// </example>
        [KalkExport("float3", CategoryVectorTypeConstructors)]
        public KalkVector<float> CreateFloat3(params object[] arguments) => Float3Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 4 `float` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> float4(1..4)
        /// # float4(1..4)
        /// out = float4(1, 2, 3, 4)
        /// >>> float4(10, 11, 12, 13)
        /// # float4(10, 11, 12, 13)
        /// out = float4(10, 11, 12, 13)
        /// ```
        /// </example>
        [KalkExport("float4", CategoryVectorTypeConstructors)]
        public KalkVector<float> CreateFloat4(params object[] arguments) => Float4Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 8 `float` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> float8(1..8)
        /// # float8(1..8)
        /// out = float8(1, 2, 3, 4, 5, 6, 7, 8)
        /// >>> float8(10, 11, 12, 13, 14, 15, 16, 17)
        /// # float8(10, 11, 12, 13, 14, 15, 16, 17)
        /// out = float8(10, 11, 12, 13, 14, 15, 16, 17)
        /// ```
        /// </example>
        [KalkExport("float8", CategoryVectorTypeConstructors)]
        public KalkVector<float> CreateFloat8(params object[] arguments) => Float8Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 16 `float` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> float16(1..16)
        /// # float16(1..16)
        /// out = float16(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
        /// >>> float16(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
        /// # float16(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
        /// out = float16(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
        /// ```
        /// </example>
        [KalkExport("float16", CategoryVectorTypeConstructors)]
        public KalkVector<float> CreateFloat16(params object[] arguments) => Float16Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 2 `double` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> double2(1..2)
        /// # double2(1..2)
        /// out = double2(1, 2)
        /// >>> double2(10, 11)
        /// # double2(10, 11)
        /// out = double2(10, 11)
        /// ```
        /// </example>
        [KalkExport("double2", CategoryVectorTypeConstructors)]
        public KalkVector<double> CreateDouble2(params object[] arguments) => Double2Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 3 `double` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> double3(1..3)
        /// # double3(1..3)
        /// out = double3(1, 2, 3)
        /// >>> double3(10, 11, 12)
        /// # double3(10, 11, 12)
        /// out = double3(10, 11, 12)
        /// ```
        /// </example>
        [KalkExport("double3", CategoryVectorTypeConstructors)]
        public KalkVector<double> CreateDouble3(params object[] arguments) => Double3Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 4 `double` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> double4(1..4)
        /// # double4(1..4)
        /// out = double4(1, 2, 3, 4)
        /// >>> double4(10, 11, 12, 13)
        /// # double4(10, 11, 12, 13)
        /// out = double4(10, 11, 12, 13)
        /// ```
        /// </example>
        [KalkExport("double4", CategoryVectorTypeConstructors)]
        public KalkVector<double> CreateDouble4(params object[] arguments) => Double4Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a vector of 8 `double` items.</summary>
        /// <example>
        /// ```kalk
        /// >>> double8(1..8)
        /// # double8(1..8)
        /// out = double8(1, 2, 3, 4, 5, 6, 7, 8)
        /// >>> double8(10, 11, 12, 13, 14, 15, 16, 17)
        /// # double8(10, 11, 12, 13, 14, 15, 16, 17)
        /// out = double8(10, 11, 12, 13, 14, 15, 16, 17)
        /// ```
        /// </example>
        [KalkExport("double8", CategoryVectorTypeConstructors)]
        public KalkVector<double> CreateDouble8(params object[] arguments) => Double8Constructor.Invoke(Engine, arguments);


        /// <summary>Creates a 2 (rows) x 2 (columns) matrix of bool.</summary>
        [KalkExport("bool2x2", CategoryMatrixConstructors)]
        public KalkMatrix<KalkBool> CreateBool2x2(params object[] arguments) => Bool2x2Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 2 (rows) x 3 (columns) matrix of bool.</summary>
        [KalkExport("bool2x3", CategoryMatrixConstructors)]
        public KalkMatrix<KalkBool> CreateBool2x3(params object[] arguments) => Bool2x3Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 2 (rows) x 4 (columns) matrix of bool.</summary>
        [KalkExport("bool2x4", CategoryMatrixConstructors)]
        public KalkMatrix<KalkBool> CreateBool2x4(params object[] arguments) => Bool2x4Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 3 (rows) x 2 (columns) matrix of bool.</summary>
        [KalkExport("bool3x2", CategoryMatrixConstructors)]
        public KalkMatrix<KalkBool> CreateBool3x2(params object[] arguments) => Bool3x2Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 3 (rows) x 3 (columns) matrix of bool.</summary>
        [KalkExport("bool3x3", CategoryMatrixConstructors)]
        public KalkMatrix<KalkBool> CreateBool3x3(params object[] arguments) => Bool3x3Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 3 (rows) x 4 (columns) matrix of bool.</summary>
        [KalkExport("bool3x4", CategoryMatrixConstructors)]
        public KalkMatrix<KalkBool> CreateBool3x4(params object[] arguments) => Bool3x4Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 4 (rows) x 2 (columns) matrix of bool.</summary>
        [KalkExport("bool4x2", CategoryMatrixConstructors)]
        public KalkMatrix<KalkBool> CreateBool4x2(params object[] arguments) => Bool4x2Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 4 (rows) x 3 (columns) matrix of bool.</summary>
        [KalkExport("bool4x3", CategoryMatrixConstructors)]
        public KalkMatrix<KalkBool> CreateBool4x3(params object[] arguments) => Bool4x3Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 4 (rows) x 4 (columns) matrix of bool.</summary>
        [KalkExport("bool4x4", CategoryMatrixConstructors)]
        public KalkMatrix<KalkBool> CreateBool4x4(params object[] arguments) => Bool4x4Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 2 (rows) x 2 (columns) matrix of int.</summary>
        [KalkExport("int2x2", CategoryMatrixConstructors)]
        public KalkMatrix<int> CreateInt2x2(params object[] arguments) => Int2x2Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 2 (rows) x 3 (columns) matrix of int.</summary>
        [KalkExport("int2x3", CategoryMatrixConstructors)]
        public KalkMatrix<int> CreateInt2x3(params object[] arguments) => Int2x3Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 2 (rows) x 4 (columns) matrix of int.</summary>
        [KalkExport("int2x4", CategoryMatrixConstructors)]
        public KalkMatrix<int> CreateInt2x4(params object[] arguments) => Int2x4Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 3 (rows) x 2 (columns) matrix of int.</summary>
        [KalkExport("int3x2", CategoryMatrixConstructors)]
        public KalkMatrix<int> CreateInt3x2(params object[] arguments) => Int3x2Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 3 (rows) x 3 (columns) matrix of int.</summary>
        [KalkExport("int3x3", CategoryMatrixConstructors)]
        public KalkMatrix<int> CreateInt3x3(params object[] arguments) => Int3x3Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 3 (rows) x 4 (columns) matrix of int.</summary>
        [KalkExport("int3x4", CategoryMatrixConstructors)]
        public KalkMatrix<int> CreateInt3x4(params object[] arguments) => Int3x4Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 4 (rows) x 2 (columns) matrix of int.</summary>
        [KalkExport("int4x2", CategoryMatrixConstructors)]
        public KalkMatrix<int> CreateInt4x2(params object[] arguments) => Int4x2Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 4 (rows) x 3 (columns) matrix of int.</summary>
        [KalkExport("int4x3", CategoryMatrixConstructors)]
        public KalkMatrix<int> CreateInt4x3(params object[] arguments) => Int4x3Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 4 (rows) x 4 (columns) matrix of int.</summary>
        [KalkExport("int4x4", CategoryMatrixConstructors)]
        public KalkMatrix<int> CreateInt4x4(params object[] arguments) => Int4x4Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 2 (rows) x 2 (columns) matrix of float.</summary>
        [KalkExport("float2x2", CategoryMatrixConstructors)]
        public KalkMatrix<float> CreateFloat2x2(params object[] arguments) => Float2x2Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 2 (rows) x 3 (columns) matrix of float.</summary>
        [KalkExport("float2x3", CategoryMatrixConstructors)]
        public KalkMatrix<float> CreateFloat2x3(params object[] arguments) => Float2x3Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 2 (rows) x 4 (columns) matrix of float.</summary>
        [KalkExport("float2x4", CategoryMatrixConstructors)]
        public KalkMatrix<float> CreateFloat2x4(params object[] arguments) => Float2x4Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 3 (rows) x 2 (columns) matrix of float.</summary>
        [KalkExport("float3x2", CategoryMatrixConstructors)]
        public KalkMatrix<float> CreateFloat3x2(params object[] arguments) => Float3x2Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 3 (rows) x 3 (columns) matrix of float.</summary>
        [KalkExport("float3x3", CategoryMatrixConstructors)]
        public KalkMatrix<float> CreateFloat3x3(params object[] arguments) => Float3x3Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 3 (rows) x 4 (columns) matrix of float.</summary>
        [KalkExport("float3x4", CategoryMatrixConstructors)]
        public KalkMatrix<float> CreateFloat3x4(params object[] arguments) => Float3x4Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 4 (rows) x 2 (columns) matrix of float.</summary>
        [KalkExport("float4x2", CategoryMatrixConstructors)]
        public KalkMatrix<float> CreateFloat4x2(params object[] arguments) => Float4x2Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 4 (rows) x 3 (columns) matrix of float.</summary>
        [KalkExport("float4x3", CategoryMatrixConstructors)]
        public KalkMatrix<float> CreateFloat4x3(params object[] arguments) => Float4x3Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 4 (rows) x 4 (columns) matrix of float.</summary>
        [KalkExport("float4x4", CategoryMatrixConstructors)]
        public KalkMatrix<float> CreateFloat4x4(params object[] arguments) => Float4x4Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 2 (rows) x 2 (columns) matrix of double.</summary>
        [KalkExport("double2x2", CategoryMatrixConstructors)]
        public KalkMatrix<double> CreateDouble2x2(params object[] arguments) => Double2x2Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 2 (rows) x 3 (columns) matrix of double.</summary>
        [KalkExport("double2x3", CategoryMatrixConstructors)]
        public KalkMatrix<double> CreateDouble2x3(params object[] arguments) => Double2x3Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 2 (rows) x 4 (columns) matrix of double.</summary>
        [KalkExport("double2x4", CategoryMatrixConstructors)]
        public KalkMatrix<double> CreateDouble2x4(params object[] arguments) => Double2x4Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 3 (rows) x 2 (columns) matrix of double.</summary>
        [KalkExport("double3x2", CategoryMatrixConstructors)]
        public KalkMatrix<double> CreateDouble3x2(params object[] arguments) => Double3x2Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 3 (rows) x 3 (columns) matrix of double.</summary>
        [KalkExport("double3x3", CategoryMatrixConstructors)]
        public KalkMatrix<double> CreateDouble3x3(params object[] arguments) => Double3x3Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 3 (rows) x 4 (columns) matrix of double.</summary>
        [KalkExport("double3x4", CategoryMatrixConstructors)]
        public KalkMatrix<double> CreateDouble3x4(params object[] arguments) => Double3x4Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 4 (rows) x 2 (columns) matrix of double.</summary>
        [KalkExport("double4x2", CategoryMatrixConstructors)]
        public KalkMatrix<double> CreateDouble4x2(params object[] arguments) => Double4x2Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 4 (rows) x 3 (columns) matrix of double.</summary>
        [KalkExport("double4x3", CategoryMatrixConstructors)]
        public KalkMatrix<double> CreateDouble4x3(params object[] arguments) => Double4x3Constructor.Invoke(Engine, arguments);
        /// <summary>Creates a 4 (rows) x 4 (columns) matrix of double.</summary>
        [KalkExport("double4x4", CategoryMatrixConstructors)]
        public KalkMatrix<double> CreateDouble4x4(params object[] arguments) => Double4x4Constructor.Invoke(Engine, arguments);
    }
}
